### ISSUE TITLE
Bug report: Mismatch in structure cases between svFSI and svFSIplus with respect to viscosity and HO model

### ISSUE THREAD

**Issue by zinanhu0810** [SimVascular/svMultiPhysics#262]
### Description

I am running the same structural test cases (LV passive filling) using svFSI and svFSIplus, but the results (e.g., pressure on the surface) are noticeably different. We tested several potential simulation parameters, and viscosity, the Holzapfel material model, and fiber direction seem to be leading to these differences.
[Structural_cases.zip](https://github.com/user-attachments/files/16821330/Structural_cases.zip)
![svFSI_Hol_fibdrn](https://github.com/user-attachments/assets/26ee75ae-a40a-4e82-be3e-83244f9549aa)
![svFSI_Hol_viss](https://github.com/user-attachments/assets/d2d709d2-e1ed-4aa6-945b-acb320c0d866)
![svFSI_nHK_viss](https://github.com/user-attachments/assets/8eb7395c-9346-411c-b60d-97848556eae3)

### Reproduction

Running the three test cases above using svFSI and svFSIplus respectively.

### Expected behavior

The two solvers give the same results. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by aabrown100-git** [comment]
@zinanhu0810 When we talked last, I think you said this mismatch is fixed. Can you confirm whether this is still an issue or not?

**Comment by zinanhu0810** [comment]
This issue has been fixed in the commit with the updated HO material model.(https://github.com/SimVascular/svMultiPhysics/commit/f9fe6fe4b5025c54188aad4c1e0859d578230d70)
