### ISSUE TITLE
The location of the Eigen header files are not set 

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svMultiPhysics#304]
### Description

The Eigen header files should be included from svFSIplus/Code/ThirdParty/eigen when building.

However, there is no `include_directories` statement for Eigen in svFSIplus/Code/Source/svFSI/CMakeLists.txt file so the build   will not include these headers.

I think there is another package (VTK ?) that is finding Eigen and setting the include file path. 

### Reproduction

Try to build without an installed Eigen.

### Expected behavior

The build should use the Eigen included in Thirdparty.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
Maybe we should not have Eigen in the svFSIplus Thirdparty, might could just use  CMake `FetchContent`.

**Comment by ktbolt** [comment]
For MacOS I have tried to set the build to use the Eigen installed in `ThirdParty` but CMake insists on using the system Eigen that is installed when installing VTK. 

However, this does work as expected for a simple CMake test.

**Comment by ktbolt** [comment]
Adding 
```
include_directories(${SV_SOURCE_DIR}/ThirdParty/eigen/include)
```
 to `solver/CMakeLists.txt` does the right thing at least on MacOS. 

Note that this is really not a good way to add include file dependencies, explicitly giving the path to ThirdParty.

**Comment by ktbolt** [comment]
I tested on Ubuntu 20, looks good.

**Comment by aabrown100-git** [comment]
Fixed in https://github.com/SimVascular/svMultiPhysics/pull/317
