### ISSUE TITLE
Usage of prismatic/wedge elements in the code 

### ISSUE THREAD

**Issue by msbazzi** [SimVascular/svMultiPhysics#312]
### Description

When trying to use prismatic elements couple problems came up:

1 - In read_mesh.cpp in function _check_wedge_conn(mshType& mesh)_  there are two swap lines that are generating the wrong connectivity matrix. Is there a reason for them to be there? @ktbolt @zasexton @dcodoni 

2 -  In VtkData.cpp in function _VtkVtuData::VtkVtuDataImpl::set_connectivity(const int nsd, const Array<int>& conn, const int pid)_ for vtk_cell_type there is no wedge type defined. 

3 - In nn_elem_props.h in function _set_3d_element_props_ the wedge shape functions should be linear not quadratic

4 - Remove the warning about the second derivative of wedge element type

5 -  In nn_elem_gip.h function get_element_gauss_int_data we need to add a case for wedge element type

### Reproduction

Try to run a wedge grid and it would prompt an error that quadratic shape functions are not supported for wedge, associated to [3] and [4]. Once that is fixed, will prompt an error about the a node not being found in the mapping between the face and the volumetric mesh, which is associated to the [1]. 
Finally, when the previous error is fixed, the code will run until tries to save a vtu file, and i will throw a runtime error, which is associated to [5].   

### Expected behavior

I expect to run a prismatic mesh and obtain results without any issues. 

### Additional context

I already fixed the issues, and it is working fine. But before doing a pr, I would like to understand what the reason behind the swap, and we can just remove it without further complications.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@msbazzi Please add some data to test this.

**Comment by ktbolt** [comment]
@msbazzi The wedge check is wrong, `a` and `b` are off by 1

https://github.com/SimVascular/svMultiPhysics/blob/39f0b52a33e19f75418f3341fa895a6f433227c6/Code/Source/solver/read_msh.cpp#L760-L763

should be 
```
a = 3;
b = 4;
```

**Comment by msbazzi** [comment]
@ktbolt you can use the mesh https://github.com/msbazzi/Prismatic-Mesh from this repository to test it.

**Comment by msbazzi** [comment]
> @msbazzi The wedge check is wrong, `a` and `b` are off by 1
> 
> https://github.com/SimVascular/svMultiPhysics/blob/39f0b52a33e19f75418f3341fa895a6f433227c6/Code/Source/solver/read_msh.cpp#L760-L763
> 
> should be
> 
> ```
> a = 3;
> b = 4;
> ```

Yes! You are right! I will fix that and leave the swap
